# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsection',
            new_name='Type',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='sub_percentage',
            new_name='percentage',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='subsection_text',
            new_name='type_text',
        ),
    ]
