# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_auto_20171013_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='type_text',
            new_name='section_text',
        ),
    ]
