# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 01:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0004_auto_20171016_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=50)),
                ('mark', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='PHYS1001', max_length=8),
        ),
    ]
