# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0005_auto_20171016_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='Course', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.CharField(default='Course', max_length=10),
        ),
    ]
