# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0006_auto_20171019_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course_fk',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='calculate.Course'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_fk',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='section', to='calculate.Section'),
        ),
    ]
