# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0009_auto_20171019_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_section',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_section', to='calculate.Section'),
        ),
    ]
