# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0010_assignment_assignment_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course_fk',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_fk',
        ),
        migrations.AddField(
            model_name='section',
            name='section_course',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='calculate.Course'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculate.Section'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_section',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='calculate.Section'),
        ),
    ]
