# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0011_auto_20171022_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='type',
            new_name='atype',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='type',
            new_name='atype',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculate.Course'),
        ),
    ]
