# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0014_auto_20171023_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_text',
            new_name='section_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='percentage',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculate.Course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculate.Section'),
        ),
    ]
