# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0015_auto_20171023_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_text',
            new_name='course_name',
        ),
    ]
