# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calculations.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_self',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculations.Assignment', verbose_name='Assignment'),
        ),
    ]
